### ISSUE TITLE
Time-consuming plugin (bloated plugin?)

### ISSUE THREAD

**Issue by tapyu** [egyptianbman/zsh-git-worktrees#2]
This plugin increased shell startup time from a tenth of a second to over half a second. That is unbearable. I suppose this plugin is bloated.

[Screencast from 2023-10-12 16-33-00.webm](https://github.com/egyptianbman/zsh-git-worktrees/assets/22801918/aae1fda4-9aba-4d28-a324-a902dd56e9ec)

That was a fortunate run. Some initializations can reach up to 0.6 seconds.

**Comment by egyptianbman** [comment]
One can argue that https://github.com/egyptianbman/zsh-git-worktrees/blob/main/zsh-git-worktrees.zsh#L9 isn't necessary to be part of this plugin, that is likely where the delay comes from.

Also, I would suggest executing `time zsh -i -c exit` to test startup time instead of simply `time zsh`.

PRs are welcome, thanks!
